#!/usr/bin/env python3
"""Rewrite the shape table in app/models/modeling.py from shapes.js.

``modeling.place`` puts a point *on* a sculpted mesh, which needs each
mesh's native size and centre exactly as ``static/js/engine/shapes.js`` bakes
them.  Those numbers used to be copied across by hand; this asks node for
them and rewrites the generated block between the two markers in
modeling.py, so a new or reshaped mesh is one command away from being
placeable in Python:

    python3 tools/shapes_table.py          # rewrite the table
    python3 tools/shapes_table.py --check  # exit 1 if it is out of date

Node is a development dependency only: the site itself never runs it.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHAPES_JS = os.path.join(ROOT, "static", "js", "engine", "shapes.js")
MODELING = os.path.join(ROOT, "app", "models", "modeling.py")
BEGIN = "    # --- generated by tools/shapes_table.py: do not edit by hand ---\n"
END = "    # --- end of generated shapes ---\n"


def measure() -> dict:
    script = ("require(%s); var S = globalThis.Shapes;"
              "process.stdout.write(JSON.stringify({native: S.native, centre: S.centre}));"
              % json.dumps(SHAPES_JS))
    out = subprocess.run(["node", "-e", script], check=True, capture_output=True,
                         text=True).stdout
    return json.loads(out)


def rows(data: dict) -> str:
    def num(v: float) -> str:
        v = round(float(v), 4)
        return "0" if v == 0 else ("%g" % v)

    lines = []
    for name in data["native"]:
        size = ", ".join(num(v) for v in data["native"][name])
        centre = ", ".join(num(v) for v in data["centre"][name])
        lines.append('    "%s": {"size": [%s], "centre": [%s]},\n' % (name, size, centre))
    return "".join(lines)


def main(argv) -> int:
    check = "--check" in argv
    data = measure()
    text = open(MODELING, encoding="utf-8").read()
    if BEGIN not in text or END not in text:
        print("modeling.py has no generated block to rewrite", file=sys.stderr)
        return 2
    head, rest = text.split(BEGIN, 1)
    _old, tail = rest.split(END, 1)
    fresh = head + BEGIN + rows(data) + END + tail
    if check:
        if fresh != text:
            print("app/models/modeling.py's shape table is out of date: "
                  "run python3 tools/shapes_table.py")
            return 1
        print("shape table up to date (%d shapes)" % len(data["native"]))
        return 0
    if fresh != text:
        with open(MODELING, "w", encoding="utf-8") as handle:
            handle.write(fresh)
    print("wrote %d shapes into app/models/modeling.py" % len(data["native"]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
